#! /usr/bin/env python
import re

from waf_dynamo import apidoc_extract_task

def init(ctx):
    pass

def configure(conf):
    pass

def build(bld):
    platforms = ['arm.*?ios', 'arm.*?android']
    source = next(
        ('iac_stub.cpp' for p in platforms if re.match(p, bld.env.PLATFORM)),
        'iac_null.cpp',
    )
    bld.stlib(features = 'cxx',
              includes = '.',
              source = source,
              target = 'iacext')

    apidoc_extract_task(bld, ['iac_doc.h'])
