#! /usr/bin/env python
import re
from waf_dynamo import apidoc_extract_task

def configure(conf):
    pass

def build(bld):
    platforms = ['arm.*?ios', 'arm.*?android', 'x86_64-ios', 'web']
    source = next(
        ('iap_stub.cpp' for p in platforms if re.match(p, bld.env.PLATFORM)),
        'iap_null.cpp',
    )
    bld.stlib(features = 'cxx',
              includes = '.',
              source = source,
              target = 'iapext')

    apidoc_extract_task(bld, ['iap_doc.h'])
