#! /usr/bin/env python

import sys, os, re
import waf_dynamo

def configure(conf):
    conf.env['SCRIPT_DOC'] = os.path.abspath('src/script_doc.py')

def build(bld):
    files = bld.path.ant_glob('*.apidoc_')
    for source in files:
        namespace, _ = os.path.splitext(source.name)
        bld(
            source=source,
            target=f'{namespace}_doc.sdoc',
            rule='python ${SCRIPT_DOC} ${SRC} ${TGT}',
        )
        bld(
            source=source,
            target=f'{namespace}_doc.json',
            rule='python ${SCRIPT_DOC} -t json ${SRC} ${TGT}',
        )
        bld(
            source=source,
            target=f'{namespace}_doc.script_api',
            rule='python ${SCRIPT_DOC} -t script_api ${SRC} ${TGT}',
        )

        bld.install_files('${PREFIX}/share/doc', f'{namespace}_doc.sdoc')
        bld.install_files('${PREFIX}/share/doc', f'{namespace}_doc.json')
        bld.install_files('${PREFIX}/share/doc', f'{namespace}_doc.script_api')

def options(opt):
    opt.load('waf_dynamo')
