#! /usr/bin/env python
import os, re

from waf_dynamo import apidoc_extract_task

def init(ctx):
    pass

def configure(conf):
    pass

def build(bld):
    platforms = ['arm.*?ios', 'arm.*?android', '.*?web']
    source = next(
        (
            'facebook_stub.cpp'
            for p in platforms
            if re.match(p, bld.env.PLATFORM)
        ),
        'facebook_null.cpp',
    )
    bld.stlib(features = 'cxx',
              includes = '.',
              source = source,
              target = 'facebookext')

    apidoc_extract_task(bld, ['facebook_doc.h'])
